# Generated by Django 2.0.6 on 2018-12-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('case_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('case_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'case_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.IntegerField(primary_key=True, serialize=False)),
                ('court_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'court',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lawer',
            fields=[
                ('lawer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lawer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lawer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('case_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
    ]
